# Generated by Django 5.0 on 2024-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid1', models.CharField(max_length=50)),
                ('imsi1', models.CharField(max_length=50)),
                ('msisdn1', models.CharField(max_length=50)),
                ('iccid2', models.CharField(max_length=50)),
                ('imsi2', models.CharField(max_length=50)),
                ('msisdn2', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('activation', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
            ],
        ),
    ]
