# Generated by Django 4.0.4 on 2022-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICCID1', models.CharField(max_length=50)),
                ('IMSI1', models.CharField(max_length=50)),
                ('MSISDN1', models.CharField(max_length=50)),
                ('ICCID2', models.CharField(max_length=50)),
                ('IMSI2', models.CharField(max_length=50)),
                ('MSISDN2', models.CharField(max_length=50)),
                ('IMEI', models.CharField(max_length=50)),
                ('STATUS', models.CharField(choices=[('ACTIVATED', 'active'), ('INACTIVE', 'not active')], default='INACTIVE', max_length=50)),
            ],
        ),
    ]
