# Generated by Django 4.0.4 on 2022-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstiot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICCID1', models.CharField(max_length=50)),
                ('MSISDN1', models.CharField(max_length=50)),
                ('STATUS', models.CharField(choices=[('ACTIVATED', 'active'), ('INACTIVE', 'not active')], default='INACTIVE', max_length=50)),
            ],
        ),
    ]
