# Generated by Django 4.0.4 on 2022-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstiot', '0002_branch1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICCID2', models.CharField(max_length=50)),
                ('MSISDN2', models.CharField(max_length=50)),
                ('STATUS', models.CharField(choices=[('ACTIVATED', 'active'), ('INACTIVE', 'not active')], default='INACTIVE', max_length=50)),
            ],
        ),
    ]
