# Generated by Django 4.0.4 on 2022-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vstiot', '0004_branch3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch3',
            name='STATUS',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'not active')], default='INACTIVE', max_length=50),
        ),
    ]
