# Generated by Django 4.0.4 on 2022-06-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vstiot', '0006_alter_branch1_status_alter_branch2_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch1',
            old_name='ICCID1',
            new_name='iccid1',
        ),
        migrations.RenameField(
            model_name='branch1',
            old_name='MSISDN1',
            new_name='msisdn1',
        ),
        migrations.RenameField(
            model_name='branch1',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='branch2',
            old_name='ICCID2',
            new_name='iccid2',
        ),
        migrations.RenameField(
            model_name='branch2',
            old_name='MSISDN2',
            new_name='msisdn2',
        ),
        migrations.RenameField(
            model_name='branch2',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='branch3',
            old_name='ICCID1',
            new_name='iccid1',
        ),
        migrations.RenameField(
            model_name='branch3',
            old_name='IMEI',
            new_name='imei',
        ),
        migrations.RenameField(
            model_name='branch3',
            old_name='SERIAL',
            new_name='serial',
        ),
        migrations.RenameField(
            model_name='branch3',
            old_name='STATUS',
            new_name='status',
        ),
    ]
